workflows:
  android-build:
    name: Build Android
    environment:
      node: latest
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova
      - name: Prepare Project
        script: |
          cordova platform add android
      - name: Build Android
        script: |
          cordova build android
    artifacts:
      - platforms/android/app/build/outputs/apk/debug/*.apk
