workflows:
  android-debug:
    name: Build Android Debug
    environment:
      node: latest
    scripts:
      - name: Install Cordova
        script: npm install -g cordova
      - name: Install Dependencies
        script: npm install
      - name: Build Android
        script: |
          cordova platform add android
          cordova build android
    artifacts:
      - platforms/android/app/build/outputs/apk/debug/*.apk
