workflows:
  my-workflow:
    name: Build Application
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build
        script: npm run build
